### ISSUE TITLE
Scraper errors

### ISSUE THREAD

**Issue by snovvmann** [AnsonLai/TeslaServiceManualScraper#14]
Hi, thanks for creating this script.  I am receiving the error below.  Any idea why?  

Also, in case it mattered, I noticed that the script does not log in directly to service.tesla.com, rather, it logs into tesla.com.  After it eventually gets to the manual I specified, it fails.

`DevTools listening on ws://127.0.0.1:57338/devtools/browser/cd79339b-94d9-4d66-af54-37bfc30
****** SESSION LOADED ******
[7452:19956:0129/225725.215:ERROR:device_event_log_impl.cc(215)] [22:57:25.215] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[7452:19956:0129/225725.216:ERROR:device_event_log_impl.cc(215)] [22:57:25.216] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Traceback (most recent call last):
  File "c:\users\j\downloads\ts\scrape.py", line 273, in <module>
    run()
  File "c:\users\j\downloads\ts\scrape.py", line 262, in run
    driver.get_index()
  File "c:\users\j\downloads\ts\scrape.py", line 53, in get_index
    window1 = driver.window_handles[1]
IndexError: list index out of range`

**Comment by webbrain-one** [comment]
Hi! Thanks for reporting this. I’ve just opened a PR to address the `IndexError` you encountered: [#16](https://github.com/AnsonLai/TeslaServiceManualScraper/pull/16). 

The crash was happening because the script was trying to access the second browser window before it had fully loaded. The update adds a proper wait condition for the new window/tab to open and safely handles the switch, which should resolve the crash. (The USB errors in the logs are just standard Chromium warnings on Windows and can be safely ignored.)

Feel free to give it a try when you have a chance and let me know how it goes. Thanks again for the detailed report!
