### ISSUE TITLE
reCaptia issue, and then an "Access Denied" error

### ISSUE THREAD

**Issue by imthisguymike** [AnsonLai/TeslaServiceManualScraper#4]
<img width="848" alt="Screen Shot 2022-05-23 at 18 17 42" src="https://user-images.githubusercontent.com/49290119/169914134-6f46bf27-83a6-49b7-b9dc-27445739017b.png">

It passes the creds, but there's a recaptia box requiring checking, after it failed I tried again, where I checked the box and did the human test, and then I get access denied. 

Logging in manually with my account works fine though.

**Comment by imthisguymike** [comment]
Also when accessing https://service.tesla.com/docs/Model3/ServiceManual/en-us/index.html after logging in (I have a Model 3) I get this:
<img width="1340" alt="Screen Shot 2022-05-23 at 18 29 40" src="https://user-images.githubusercontent.com/49290119/169915085-0f3d74c3-8468-428b-a0c5-611cb1b8ebc6.png">

And on the service page it redirects to I only see these options:
<img width="1518" alt="Screen Shot 2022-05-23 at 18 31 05" src="https://user-images.githubusercontent.com/49290119/169915185-94cefbb9-ed8d-4e4e-ab40-94b916487fe8.png">

**Comment by AnsonLai** [comment]
I've been scraping it for a while and only saw the recaptcha box once, so I assumed you had to be pretty aggregious to see it.  I inputted a login delay variable to intercept manually if it happens.

Also, that same error appeared before I started using selenium stealth (they won't let obvious bots login).

**Comment by AnsonLai** [comment]
For the second issue, you actually need to claim the free service manuals first.

https://service.tesla.com/service-subscription

**Comment by imthisguymike** [comment]
I fixed the second part, should I download your new code for the delay? I also installed the stealth

**Comment by imthisguymike** [comment]
Now I am getting this after refreshing your code:
```
C:\Users\Bond\TeslaServiceManualScraper>py scrape.py
Traceback (most recent call last):
  File "C:\Users\Bond\TeslaServiceManualScraper\scrape.py", line 10, in <module>
    from secrets import tesla_login
  File "C:\Users\Bond\TeslaServiceManualScraper\secrets.py", line 3, in <module>
    from scrape import login_delay
  File "C:\Users\Bond\TeslaServiceManualScraper\scrape.py", line 10, in <module>
    from secrets import tesla_login
ImportError: cannot import name 'tesla_login' from partially initialized module 'secrets' (most likely due to a circular import) (C:\Users\Bond\TeslaServiceManualScraper\secrets.py)
```

**Comment by AnsonLai** [comment]
Fixed!

**Comment by imthisguymike** [comment]
Confirmed, it is working fine now! Thanks!
